<?xml version="1.0" encoding="utf-8"?><testsuite errors="0" failures="1" name="pytest" skips="0" tests="8" time="0.392"><testcase classname="pytests.test_index" file="pytests/test_index.py" line="10" name="test_conda_environment_activated" time="0.001264810562133789"></testcase><testcase classname="pytests.test_index" file="pytests/test_index.py" line="13" name="test_restaurant_name_func" time="0.0005373954772949219"></testcase><testcase classname="pytests.test_index" file="pytests/test_index.py" line="18" name="test_restaurant_rating_func" time="0.0005435943603515625"></testcase><testcase classname="pytests.test_index" file="pytests/test_index.py" line="23" name="test_is_better_func" time="0.0005221366882324219"></testcase><testcase classname="pytests.test_index" file="pytests/test_index.py" line="29" name="test_is_cheaper_func" time="0.0005249977111816406"></testcase><testcase classname="pytests.test_index" file="pytests/test_index.py" line="35" name="test_high_rating_func" time="0.0005335807800292969"></testcase><testcase classname="pytests.test_index" file="pytests/test_index.py" line="41" name="test_mean_review_count_func" time="0.0005564689636230469"></testcase><testcase classname="pytests.test_index" file="pytests/test_index.py" line="45" name="test_mediam_review_count_func" time="0.0024869441986083984"><failure message="AssertionError: assert 652.0 == 1284.5
 +  where 652.0 = median_review_count([{&apos;categories&apos;: [{&apos;alias&apos;: &apos;seafood&apos;, &apos;title&apos;: &apos;Seafood&apos;}, {&apos;alias&apos;: &apos;gourmet&apos;, &apos;title&apos;: &apos;Gourmet&apos;}, {&apos;alias&apos;: &apos;Shellf...808088832532, &apos;longitude&apos;: -106.619402244687}, &apos;display_phone&apos;: &apos;(505) 266-0550&apos;, &apos;distance&apos;: 4033.6583235266075, ...}])">def test_mediam_review_count_func():
        assert &apos;median_review_count&apos; in ipynb.fs.full.index.__dict__, &quot;The median_review_count function must be defined&quot;
&gt;       assert median_review_count(restaurant_list) == 1284.5
E       AssertionError: assert 652.0 == 1284.5
E        +  where 652.0 = median_review_count([{&apos;categories&apos;: [{&apos;alias&apos;: &apos;seafood&apos;, &apos;title&apos;: &apos;Seafood&apos;}, {&apos;alias&apos;: &apos;gourmet&apos;, &apos;title&apos;: &apos;Gourmet&apos;}, {&apos;alias&apos;: &apos;Shellf...808088832532, &apos;longitude&apos;: -106.619402244687}, &apos;display_phone&apos;: &apos;(505) 266-0550&apos;, &apos;distance&apos;: 4033.6583235266075, ...}])

pytests/test_index.py:48: AssertionError</failure><system-out>[350, 604, 1200, 1369, 1588, 2455]
0
</system-out></testcase></testsuite>